### PR TITLE
Add icon to Chart.yml for happa

### PR DESCRIPTION
**Pull request by mogottsch**
Towards https://github.com/giantswarm/roadmap/issues/1248

### CODE REVIEW

**Review by stone-z — APPROVED** [review]

**Review by stone-z — CHANGES_REQUESTED** [review]
Wrong Chart

**Comment by stone-z** [comment]
This should be in https://github.com/giantswarm/starboard-app/blob/main/helm/starboard-app/Chart.yaml

**Comment by mogottsch** [comment]
@stone-z Thanks for pointing that out.
I added it to the correct `Chart.yaml` and also updated the icon in the other `Chart.yaml`.

**Comment by stone-z** [comment]
What is the reason/difference behind modifying the "inner" chart as well? Where does that show up?
Asking because I'd prefer not to modify the subtree without a good reason because it makes our lives much more difficult.

**Comment by mogottsch** [comment]
I don't think it is necessary. If it makes your lives harder, I will revert it :)

**Review by stone-z — APPROVED** [review]
Thanks. It wasn't until this PR that I noticed we'd deviated in that inner chart to begin with. If it is actually shown somewhere, then we will update it

**Pull request merged**
